/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BrandKitRouteImport } from './routes/brand-kit'
import { Route as CircleRouteImport } from './routes/circle'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as IngestRouteImport } from './routes/ingest'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MerchRouteImport } from './routes/merch'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PitchRouteImport } from './routes/pitch'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiWebhooksTelegramRouteImport } from './routes/api/webhooks/telegram'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandKitRoute = BrandKitRouteImport.update({
  id: '/brand-kit',
  path: '/brand-kit',
  getParentRoute: () => rootRouteImport,
} as any)
const CircleRoute = CircleRouteImport.update({
  id: '/circle',
  path: '/circle',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const IngestRoute = IngestRouteImport.update({
  id: '/ingest',
  path: '/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchRoute = MerchRouteImport.update({
  id: '/merch',
  path: '/merch',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PitchRoute = PitchRouteImport.update({
  id: '/pitch',
  path: '/pitch',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksTelegramRoute = ApiWebhooksTelegramRouteImport.update({
  id: '/api/webhooks/telegram',
  path: '/api/webhooks/telegram',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/brand-kit': typeof BrandKitRoute
  '/circle': typeof CircleRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/ingest': typeof IngestRoute
  '/login': typeof LoginRoute
  '/merch': typeof MerchRoute
  '/onboarding': typeof OnboardingRoute
  '/pitch': typeof PitchRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/studio': typeof StudioRoute
  '/timeline': typeof TimelineRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/webhooks/telegram': typeof ApiWebhooksTelegramRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/brand-kit': typeof BrandKitRoute
  '/circle': typeof CircleRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/ingest': typeof IngestRoute
  '/login': typeof LoginRoute
  '/merch': typeof MerchRoute
  '/onboarding': typeof OnboardingRoute
  '/pitch': typeof PitchRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/studio': typeof StudioRoute
  '/timeline': typeof TimelineRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/webhooks/telegram': typeof ApiWebhooksTelegramRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/brand-kit': typeof BrandKitRoute
  '/circle': typeof CircleRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/ingest': typeof IngestRoute
  '/login': typeof LoginRoute
  '/merch': typeof MerchRoute
  '/onboarding': typeof OnboardingRoute
  '/pitch': typeof PitchRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/studio': typeof StudioRoute
  '/timeline': typeof TimelineRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/webhooks/telegram': typeof ApiWebhooksTelegramRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/brand-kit'
    | '/circle'
    | '/dashboard'
    | '/forgot-password'
    | '/ingest'
    | '/login'
    | '/merch'
    | '/onboarding'
    | '/pitch'
    | '/settings'
    | '/signup'
    | '/studio'
    | '/timeline'
    | '/api/auth/$'
    | '/api/webhooks/telegram'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/brand-kit'
    | '/circle'
    | '/dashboard'
    | '/forgot-password'
    | '/ingest'
    | '/login'
    | '/merch'
    | '/onboarding'
    | '/pitch'
    | '/settings'
    | '/signup'
    | '/studio'
    | '/timeline'
    | '/api/auth/$'
    | '/api/webhooks/telegram'
  id:
    | '__root__'
    | '/'
    | '/brand-kit'
    | '/circle'
    | '/dashboard'
    | '/forgot-password'
    | '/ingest'
    | '/login'
    | '/merch'
    | '/onboarding'
    | '/pitch'
    | '/settings'
    | '/signup'
    | '/studio'
    | '/timeline'
    | '/api/auth/$'
    | '/api/webhooks/telegram'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrandKitRoute: typeof BrandKitRoute
  CircleRoute: typeof CircleRoute
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  IngestRoute: typeof IngestRoute
  LoginRoute: typeof LoginRoute
  MerchRoute: typeof MerchRoute
  OnboardingRoute: typeof OnboardingRoute
  PitchRoute: typeof PitchRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  StudioRoute: typeof StudioRoute
  TimelineRoute: typeof TimelineRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiWebhooksTelegramRoute: typeof ApiWebhooksTelegramRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand-kit': {
      id: '/brand-kit'
      path: '/brand-kit'
      fullPath: '/brand-kit'
      preLoaderRoute: typeof BrandKitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/circle': {
      id: '/circle'
      path: '/circle'
      fullPath: '/circle'
      preLoaderRoute: typeof CircleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingest': {
      id: '/ingest'
      path: '/ingest'
      fullPath: '/ingest'
      preLoaderRoute: typeof IngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merch': {
      id: '/merch'
      path: '/merch'
      fullPath: '/merch'
      preLoaderRoute: typeof MerchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pitch': {
      id: '/pitch'
      path: '/pitch'
      fullPath: '/pitch'
      preLoaderRoute: typeof PitchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/telegram': {
      id: '/api/webhooks/telegram'
      path: '/api/webhooks/telegram'
      fullPath: '/api/webhooks/telegram'
      preLoaderRoute: typeof ApiWebhooksTelegramRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrandKitRoute: BrandKitRoute,
  CircleRoute: CircleRoute,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  IngestRoute: IngestRoute,
  LoginRoute: LoginRoute,
  MerchRoute: MerchRoute,
  OnboardingRoute: OnboardingRoute,
  PitchRoute: PitchRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  StudioRoute: StudioRoute,
  TimelineRoute: TimelineRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiWebhooksTelegramRoute: ApiWebhooksTelegramRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
